### ISSUE TITLE
Add configuration

### ISSUE THREAD

**Issue by zimme** [zimme/meteor-active-route#17]
Add "global" configuration for package, as I've done with [zimme:collection-behaviours](/zimme/meteor-collection-behaviours).

Should be able to choose default `className`

Hopefully forks like [owdco:iron-router-is-selected](/owdco/meteor-iron-router-is-selected) won't be needed.

@owdco would this be enough for you to use this package instead if maintaining your own fork?

**Comment by olivier-g** [comment]
Yes it would, this would great!

**Comment by owdco** [comment]
Yes it would, this would be great!

**Comment by zimme** [comment]
I'll try and get this done as soon as possible but I don't think I'll have time available until sometime next week.

The biggest reason I wanna make this happen is that I strongly believe it's better to have as few packages as possible to do almost the same thing... less confusion for new members to the meteor community. :smile:

**Comment by zimme** [comment]
@owdco, version 2.0.0 is released under the new name `zimme:active-route`.

It adds
```js
ActiveRoute.configure({
  activeClass: 'is-selected',
  disabledClass: 'is-disabled',
});
```

How about `meteor admin set-unmigrated owdco:iron-router-is-selected` to hide it from atmosphere?

**Comment by olivier-g** [comment]
@zimme Thanks, I've removed the package. Might be cached on atmosphere, but you can I see I don't have any packages anymore now: https://atmospherejs.com/owdco

**Comment by zimme** [comment]
:+1:
