### ISSUE TITLE
Issue after updating to latest version

### ISSUE THREAD

**Issue by ciwolsey** [zimme/meteor-active-route#30]
Getting the following spammed in my console:
```
Exception in template helper: Error: Match error: Unknown key in field route
```
I'm using active-route on about 8 routes. Removed the package and references and this fixed the problem.

**Comment by zimme** [comment]
Which version? Iron:router or flow-router? Template helper or javascript helper? Which syntax? {{isActiveRoute 'home'}} or {{IsActiveRoute regex='home'}} or some other syntax?

**Comment by zimme** [comment]
So I'm 99% sure you're using `{{isActiveRoute route="home"}}` instead of `{{isActiveRoute name="home"}}`.

Maybe I should make `route` an alias for `name` for the `isActiveRoute`/`isNotActiveRoute` helpers.

**Comment by zimme** [comment]
I choose `name` for the `isActiveRoute` helpers because I thought it would make it clearer that `isActiveRoute` matches the route's name instead of path

**Comment by ciwolsey** [comment]
Yes I'm using "route".. It should work if I switch to "name"? That's good to know. Thanks z1mme keep up the good work. Indeed "name" is better.

**Comment by zimme** [comment]
Yes, and some version ago I actually made it possible to use this syntax too, `{{isActiveRoute 'home'}}`
