### ISSUE TITLE
Path starts with route name

### ISSUE THREAD

**Issue by 57even** [zimme/meteor-active-route#32]
`{{isActiveRoute name='companies'}}"` works great but sometimes it could be useful to have a helper to check if active route starts with the route in `name='companies'` (e.g. for paths like `/companies/company-1/`).

Right now I'm using `{{#if isActivePath regex='^\\/companies'}}` but it could be smart if I didn't need to 'hardcode' the path name in the template instead of just using the defined route name.

**Comment by zimme** [comment]
In this specific case I would name the name with the path `/companies/:_id` to `showCompany` then just use `{{isActiveRoute 'showCompany'}}` for the matching.

**Comment by zimme** [comment]
Another option is to use like `companies.company1` kinds of names for the routes if you set up all routes manually and then you can match with `{{isActiveRoute regex='^companies.'}}`

**Comment by zimme** [comment]
I'm closing this issue as answered, @mention me if you want me to re-open the issue.
