### ISSUE TITLE
Please change to "kadira:flow-router"?

### ISSUE THREAD

**Issue by thearabbit** [zimme/meteor-active-route#36]
Please change to "kadira:flow-router"?

**Comment by zimme** [comment]
When I get back from my vacation on saturday I can add it to the weak
dependencies. If you need it faster than that ill accept a complete PR,
incl changelog update

**Comment by zimme** [comment]
#37

**Comment by zimme** [comment]
Reopening this as I've fixed this, I'm just gonna try and have a stab at #35 before release.

**Comment by lsunsi** [comment]
Thanks zimme.
Just waiting the update to re-include the package in my current projects

**Comment by thearabbit** [comment]
Thanks, I waiting you :+1:
