### ISSUE TITLE
isActiveRoute not working if FlowRouter is redirecting

### ISSUE THREAD

**Issue by derwaldgeist** [zimme/meteor-active-route#40]
Scenario:

My layout consists of a main menu bar and a main canvas that changes often. In the menu bar, I have the following code:

```html
<li class="{{isActiveRoute 'root'}}"><a href="{{pathFor 'root'}}">Home</a></li>
<li class="{{isActiveRoute regex='^myGroup'}}"><a href="{{pathFor 'myGroup'}}">Menu Entry</a></li>
```
There are two routes matching '^myGroup': 'myGroup', which is the root (/) of a route group (path: /group), and 'myGroupPage' which is a sub-page in this group (path: /group/page). I'm expecting isActiveRoute to set the class to 'active' for both route names.

myGroup is a teaser page for users that are not logged-in, wheres myGroupPage is the content the user will see after login. Hence, I configured an 'triggersEnter' on both routes that will redirect to the other if the logged-in state is not correct, i.e. myGroup will redirect to myGroupPage, if the user is logged in, whereas myGroupPage will redirect to myGroup, if the user is not logged in.

Here's the router configuration for the 'myGroup' route group:

```js
var myGroupRoutes = FlowRouter.group({
  prefix: '/group'
});

myGroupRoutes.route('/', {
  // If user is logged in, redirect to sub page
  triggersEnter: [function (context, redirect) {
    if (Meteor.user()) {
      redirect('myGroupPage');
    }
  }],
  // If user is not logged in, show teaser page
  action: function () {
    BlazeLayout.render('layout', {
      mainCanvas: 'teaserPage'
    });
  },
  name: 'myGroup'
});

myGroupRoutes.route('/page', {
  // If user is not logged in, redirect to teaser page
  triggersEnter: [function (context, redirect) {
    if (!Meteor.user()) {
      redirect('myGroup');
    }
  }],
  action: function () {
    BlazeLayout.render('layout', {
      mainCanvas: 'subPage'
    });
  },
  name: 'myGroupPage'
});
```

Both pages share the same entry in the menu (i.e. the menu entry points to route 'myGroup'), and there is also another menu that allows the user to switch to the site homepage ('root'), which is the root path of the application ('/').

The problem:

If the user is not logged in and I switch between the menu items (i.e. switch between routes 'root' and 'myGroup'), the menu highlight will adjust as expected. However, if the user is logged-in and I switch between 'root' and 'myGroup', the menu item will not be updated to match 'myGroup', it will stick to the home menu entry. It seems as if there is a problem if FlowRouter is redirecting to a sub route of the current route. In this case, isActiveRoute will not be set to 'active' even if the regexp is still matching.

**Comment by zimme** [comment]
Thank you very much for this. On first sight it seems like this might be a problem in flow-router, but I'll look into it and see what I find.

**Comment by derwaldgeist** [comment]
Your'e welcome, thanks for having a look at it!

**Comment by derwaldgeist** [comment]
Any updates on this?

**Comment by zimme** [comment]
Hey, no I'm sorry haven't had time to work with this package in a while. I'll try and carve out some time this weekend.

**Comment by derwaldgeist** [comment]
@zimme: Thanks for the quick reply. I did some debugging now myself and posted an issue for FlowRouter: https://github.com/kadirahq/flow-router/issues/314 as I found out that it won't reactively update its reactive functions if a redirect to a sub-route in a group takes place. At least I suspect it's not doing this.

**Comment by zimme** [comment]
Thanks a bunch for taking the time to track this down

**Comment by derwaldgeist** [comment]
No problem, I need this functionality :-) Let's see what the FlowRouter guys say.

**Comment by derwaldgeist** [comment]
The bug in FlowRouter is now fixed, so I am closing this.

**Comment by zimme** [comment]
:+1: Nice! Thank you for taking the initiative on this one, much appreciated.
