### ISSUE TITLE
Somewhat of a crazy issue but active router has a conflict with Parsely.js  

### ISSUE THREAD

**Issue by almogdesign** [zimme/meteor-active-route#43]
I have a form setup using Parsely.js the route is create-post if I have the following code for the active route parsely.js does not work it's never triggered 
```javascript
<li class="{{isActiveRoute regex='create-post'}}">
<a href="{{pathFor 'create-post'}}" id="create-post"><i class="glyphicon glyphicon-plus"></i><span class="title">{{mf 'create-post' 'Create Post'}}</span></a>
</li>
```

Seems to be a direct conflict here is the ticker I had on Parsely.js - https://github.com/guillaumepotier/Parsley.js/issues/991

**Comment by almogdesign** [comment]
Never mind the issue is 100% on my end I had create post id twice

**Comment by zimme** [comment]
Try with the latest rc release and see if that helps. Other than that it would be nice to know which router you use.

A reproduction on meteorpad.com would be awesome

**Comment by zimme** [comment]
Nice :+1:
