### ISSUE TITLE
Possible to get "starting with" regex for multiple levels?

### ISSUE THREAD

**Issue by andregoldstein** [zimme/meteor-active-route#44]
Hi there, I'm having a few issues trying to get `admin/clients` and all it's sub pages to mark as active

Have tried below but it only seems to go one level deep? Is this possible?

```
{{isActivePath regex='^admin/clients'}}
```
Ideally this would work for

```
admin/clients
admin/clients/profile
admin/clients/new
```

etc

Thanks for all your hard work on this helpful package!

**Comment by brajt** [comment]
It doesn't work because "/" has its special meaning in regex. You need to escape every such special character using "\" in front of it.

I remember zimme mentioning that support for route groups could come handy in such situations.

**Comment by zimme** [comment]
```handlebars
{{isActivePath regex='^admin\/clients'}}
```
This should work as you expect. Also the `AcitveRoute.group` and `{{isActiveGroup ...}}` thing would help, I haven't had time to get to that and it isn't a prio as it's flow-router only so I need to think about if and how I can translate it into iron-router

**Comment by andregoldstein** [comment]
Thanks both.

On 23 November 2015 at 14:48, Simon Fridlund <notifications@github.com>
wrote:

> {{isActivePath regex='^admin\/clients'}}
>
> This should work as you expect. Also the AcitveRoute.group and {{isActiveGroup
> ...}} thing would help, I haven't had time to get to that and it isn't a
> prio as it's flow-router only so I need to think about if and how I can
> translate it into iron-router
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zimme/meteor-active-route/issues/44#issuecomment-158957427>
> .
>



-- 
*André Goldstein*
*Director, Milktop*

*http://www.milktop.co.uk <http://www.milktop.co.uk>*
@MilktopDesign <https://twitter.com/MilktopDesign>

**Comment by zimme** [comment]
I'll close this as solved. I'll open another issue for `ActiveRoute.group`/`{{isActiveGroup}}` functionality.

**Comment by livimonte** [comment]
For my case (subcategories, subcategoriestwo and subcategoriesthree) this works fine:

```javascript
{{isActivePath regex='^\\/categories$|^\\/categories/'}}
```
