### ISSUE TITLE
How to use inside my package templates?

### ISSUE THREAD

**Issue by lnmunhoz** [zimme/meteor-active-route#48]
I'm trying to use this package inside my package (I'm building a layout package for my apps). But when the app loads I'm getting:

```
Exception in template helper: Error: No supported router installed. Please install iron:router or meteorhacks:flow-router.
```

The dependencies of my package are:
```
api.use('jquery');
api.use('twbs:bootstrap@3.3.5');
api.use('fortawesome:fontawesome@4.5.0');
api.use('alanning:roles@1.2.14');
api.use('zimme:active-route@2.3.3-rc.1');
```

My app uses the `kadira:flow-router` as router. I tried to add the `kadira:flow-router` as a dependency but didn't works... How can I resolve this dependency tree?

**Comment by zimme** [comment]
try adding `api.use('kadira:flow-router@<version>');` to the package too.

if the package it self doesn't need to setup it's own routes then you can just do
`api.use('kadira:flow-router@<version>', { weak: true });`

I think this is needed to make sure the router is loaded before the use of my package properly.

**Comment by lnmunhoz** [comment]
Thanks @zimme
