### ISSUE TITLE
Dynamic route name passed to isActiveRoute

### ISSUE THREAD

**Issue by andy4545** [zimme/meteor-active-route#51]
Is it possible to pass a dynamic route name to "isActiveRoute"

eg:   **menuItems** helper returns an _array of objects_ for a menu, where **label** and **routename** are properties of each object instance. 
```
{{#each menuItems}}
        <li class="{{isActiveRoute routename}}">
               {{#linkTo route=routename}}
                            {{label}}
               {{/linkTo}}
        </li>
{{/each}}
```

**Comment by zimme** [comment]
I believe that code "should" work, but it isn't?

**Comment by zimme** [comment]
Try `{{isActiveRoute name=routename}}`, if your example doesn't work

**Comment by andy4545** [comment]
My apologies - that does work.
